services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bash -c "bundle install && rm -f tmp/pids/server.pid && ./bin/dev"
    tty: true
    stdin_open: true
    volumes:
      - .:/myapp
    environment:
      TZ: Asia/Tokyo
    ports:
      - "3000:3000"
    user: "1000:1000"
